/* Check database container:
SELECT name FROM v$pdbs;
*/

ALTER SESSION SET CONTAINER = ORCL;

DROP USER HR CASCADE;

CREATE USER HR IDENTIFIED BY hr DEFAULT TABLESPACE users TEMPORARY TABLESPACE TEMP QUOTA unlimited on users QUOTA 0 on system;

GRANT CONNECT, RESOURCE TO HR;

GRANT CREATE SESSION, CREATE VIEW, CREATE TABLE, ALTER SESSION, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO HR;

GRANT CREATE SYNONYM, CREATE DATABASE LINK, UNLIMITED TABLESPACE TO HR;