SELECT parameter, value FROM nls_database_parameters
WHERE parameter LIKE 'NLS_%_FORMAT';

SELECT 
	SYSDATE,
    LOCALTIMESTAMP,
    CURRENT_TIMESTAMP,
	SYSTIMESTAMP
FROM dual;

ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT='DD/MM/YYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT='DD/MM/YYYY HH24:MI:SS TZH:TZM';

SELECT 
	SYSDATE,
    LOCALTIMESTAMP,
    CURRENT_TIMESTAMP,
	SYSTIMESTAMP
FROM dual;

SELECT 
	TO_CHAR(SYSDATE),
    TO_CHAR(LOCALTIMESTAMP),
    TO_CHAR(CURRENT_TIMESTAMP),
	TO_CHAR(SYSTIMESTAMP)
FROM dual;
